name: Upload JS build artifacts
description: "Upload built JavaScipt artifacts for use in downstream build and test steps"

runs:
    using: "composite"
    steps:
        # Upload built JS artifacts for tests
        #
        # (listed here in the same order they appear in the directory)
        - uses: actions/upload-artifact@v3
          with:
              name: perspective-dist
              path: packages/perspective/dist/

        - uses: actions/upload-artifact@v3
          with:
              name: perspective-jupyterlab-dist
              path: packages/perspective-jupyterlab/dist/

        - uses: actions/upload-artifact@v3
          with:
              name: perspective-viewer-d3fc-dist
              path: packages/perspective-viewer-d3fc/dist

        - uses: actions/upload-artifact@v3
          with:
              name: perspective-viewer-datagrid-dist
              path: packages/perspective-viewer-datagrid/dist

        - uses: actions/upload-artifact@v3
          with:
              name: perspective-viewer-openlayers-dist
              path: packages/perspective-viewer-openlayers/dist

        - uses: actions/upload-artifact@v3
          with:
              name: perspective-esbuild-plugin-dist
              path: packages/perspective-esbuild-plugin/dist

        - uses: actions/upload-artifact@v3
          with:
              name: perspective-webpack-plugin-dist
              path: packages/perspective-webpack-plugin/dist

        - uses: actions/upload-artifact@v3
          with:
              name: perspective-cli-dist
              path: packages/perspective-cli/dist

        - uses: actions/upload-artifact@v3
          with:
              name: perspective-workspace-dist
              path: packages/perspective-workspace/dist

        - uses: actions/upload-artifact@v3
          with:
              name: perspective-viewer-dist
              path: rust/perspective-viewer/dist
        ######################################################
        # Upload Jupyter artifacts for python build/test/dist
        - uses: actions/upload-artifact@v3
          with:
              name: nbextension-dist
              path: python/perspective/perspective/nbextension
              if-no-files-found: error

        - uses: actions/upload-artifact@v3
          with:
              name: labextension-dist
              path: python/perspective/perspective/labextension
              if-no-files-found: error
